services:
  - type: web
    name: mall-billing-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask patch-db && gunicorn -w 8 --timeout 120 --max-requests 1000 --max-requests-jitter 100 -b 0.0.0.0:10000 run:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CLOUD_DEMO
        value: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: mall-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: mall-db
    databaseName: mall
    user: mall_user
    plan: free
